/*
 * bsp_sd_override.c
 *
 *  Created on: 17 Apr 2026
 *      Author: adeastman
 */

#include "main.h"
#include "bsp_driver_sd.h"

/* Bring in the SD handle generated by CubeMX in sdmmc.c */
extern SD_HandleTypeDef hsd1;

/* Strong definition of BSP_SD_Init to override the weak one generated by CubeMX */
uint8_t BSP_SD_Init(void)
{
  uint8_t sd_state = MSD_OK;

  /* Check if card is present */
  if (BSP_SD_IsDetected() != SD_PRESENT)
  {
    return MSD_ERROR_SD_NOT_PRESENT;
  }

  /* 1. Initialise the hardware (starts in 1-bit mode per CubeMX config) */
  sd_state = HAL_SD_Init(&hsd1);

  if (sd_state == MSD_OK)
  {
    /* 2. WAIT for the card to be ready in 1-bit mode */
    while(HAL_SD_GetCardState(&hsd1) != HAL_SD_CARD_TRANSFER)
    {
        HAL_Delay(1);
    }

    /* 3. Safely command the card to switch to 4-bit mode! */
    if (HAL_SD_ConfigWideBusOperation(&hsd1, SDMMC_BUS_WIDE_4B) != HAL_OK)
    {
      sd_state = MSD_ERROR;
    }
  }

  return sd_state;
}
